### ISSUE TITLE
Using PHPoole CLI as non-root on Ubuntu

### ISSUE THREAD

**Issue by tschach** [PHPoole/PHPoole#122]
Hi,

I followed the installation instructions https://github.com/PHPoole/PHPoole#installation to install the PHPoole CLI application (version 2.3.1) on my Ubuntu 16.04. As a non-root user I was not able to `mv phpoole.phar /usr/local/bin/phpoole` since I do not have write permissions for `/usr/local/bin`.
I can of course `sudo mv phpoole.phar /usr/local/bin/phpoole`, but then I cannot run PHPoole as a non-root user, since it again requires write permissions to `/usr/local/bin` and throws this error:

> `PHP Fatal error:  Uncaught Humbug\SelfUpdate\Exception\FilesystemException: The directory is not writeable: /usr/local/bin. in phar:///usr/local/bin/phpoole/vendor/padraic/phar-updater/src/Updater.php:462`

As a workaround I moved it to `~/.local/bin` and added it to PATH: `PATH="$HOME/.local/bin:$PATH"`. Maybe this could be added to the Installation guidelines? I would be glad to provide a PR, also if there is a better solution to solve this issue.

Best
Tobias

**Comment by Narno** [comment]
Hello @tschach, yes it's a known problem from The `padraic/phar-updater` package.

I think the best way to resolve this issue is to add your contribution to this PR: https://github.com/humbug/phar-updater/pull/21.

Thank you! :-)

**Comment by tschach** [comment]
Thanks @Narno, will do.
