### ISSUE TITLE
Deploy to gh-pages

### ISSUE THREAD

**Issue by lex111** [PHPoole/PHPoole#154]
Hi there!

How it is better to make, using PHPoole?
Perhaps it's worth writing about this in the documentation.

**Comment by Narno** [comment]
Hello @lex111,

PHPoole has not (integrated) tool to publish/deploy generated site to gh-pages.

But, there is severals approche:
- manually, by git push the content of `_site` to your gh-pages branch
- with tools, like https://www.npmjs.com/package/gh-pages
- automated with Travis CI (https://docs.travis-ci.com/user/deployment/pages/)

**Comment by Narno** [comment]
More recipes here: https://cecil.app/documentation/publish/.
